package br.usp.ime.protocol.parser;

public enum TokenType {
	RESERVED, NUMBER, RAW, UNRECOGNIZED, MINITRANSACTION, PROBLEM, READ, WRITE, EXTENSION_COMMAND, RESULT, NOT_COMMIT, FINISH, ABORT, OPENING_CURLY_BRACE, CLOSING_CURLY_BRACE, NEW_LINE, COMMIT, TRY_AGAIN
}
