all:
	latex qualificacao.tex
	
clean:
	rm -f qualificacao.dvi qualificacao.pdf qualificacao.
	
view: all
	evince qualificacao.dvi
	
pdf: all
	dvipdf qualificacao.dvi

viewpdf: pdf
	evince qualificacao.pdf
	

